[package]
name = "fortune"
version = "0.1.0"
edition = "2021"
description = "Implements a fortune cookie / quote of the day API (RFC 865)."

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
rand = "0.8.5"
tokio = { version = "1.28.1", features = ["full"] }
